version: '3'
services:

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cook-local-main
      - MYSQL_USER=cook
      - MYSQL_PASSWORD=cook
    ports:
      - 3306:3306
    volumes:
      - ./mysql/main/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    links:
      - db

